### ISSUE TITLE
Code Bug: Interaction dataset

### ISSUE THREAD

**Issue by tribustale** [Royal-Society-Agricultural-Networks/multilayer-plant-importance#1]
When constructing the interaction matrix out of the edge list, you make use of the function edgelist2Matrix.R:
```r
## Convert an edgelist to a matrix
edgelist2Matrix <- function(elist){
  elist$lower <- as.character(elist$lower)
  elist$upper <- as.character(elist$upper)
  rows <- unique(elist$lower)
  cols <- unique(elist$upper)
  network <- matrix(0,nrow = length(rows),ncol = length(cols),dimnames = list(rows,cols))
  for (r in 1:nrow(elist)){
    lowerTaxon <- elist$lower[r]
    upperTaxon <- elist$upper[r]
    network[lowerTaxon,upperTaxon] <- elist$fortotals[r]
  }
  return(network)
}
```

Written in this way, using the data for Norwood farm multilayer network ([nore2_aggregated.csv](https://github.com/Royal-Society-Agricultural-Networks/multilayer-plant-importance/blob/90c6904dedf231cf4005d036b8a8509ff995a731/nore2_aggregated.csv)), the function is selecting the interaction strength of the **final record** that is specific of a given habitat and does not consider the value aggregated at the farm scale.

**Comment by fmwindsor** [comment]
Thanks for pointing this out! 

The bug is due to the incorrect dataset being uploaded to the repository (really sorry about this!). The current dataset has the separated interactions across each of the 10 habitats at Norwood Farm, rather than the weighted mean. 

I will add the correct dataset from Dryad (weighted mean interactions at the whole farm scale). 

The change in dataset will make no difference to the species richness based analyses (those presented in the main text of the manuscript), but may slightly alter the abundance and evenness results we report in the supporting information. 

Thanks again for finding this bug and apologies for missing this when proofing the code!!

**Comment by fmwindsor** [comment]
I have now updated the datasets and altered the code to read in the correct file. 

There are some minor changes in the plant mixes reported for the abundance and evenness based analyses which are reported in Table S1 of the manuscript, so please be aware of this when running the code (i.e., in some of the optimal plant mixes produced using the code and new data, there is 1 plant different out of 5). 

Apologies again for this bug/issue and thank you for spotting it!
